version: '3.7'

services:
  backend:
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - static:/staticfiles
    env_file:
      - ./app/.env
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend:/frontend/build
    env_file:
      - frontend/.env.local
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend:

