services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    command: npm run dev
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/build:/frontend/build
      - ./frontend/src:/frontend/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env.local
    networks:
      - app-network
    stdin_open: true
    tty: true
    restart: unless-stopped

  nginx:
    image: umitcansaran/shopping-land-nginx:1.0
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
