# Generated by Django 4.1.3 on 2023-05-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_orderitem_isretrieved_orderitem_isshipped_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InStoreOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=200, null=True)),
                ("orderType", models.CharField(blank=True, max_length=200, null=True)),
                ("isShipped", models.BooleanField(default=False)),
                ("shippedAt", models.DateTimeField(blank=True, null=True)),
                ("isRetrieved", models.BooleanField(default=False)),
                ("retrievedAt", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.product",
                    ),
                ),
                (
                    "sellerOrder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inStoreOrderItems",
                        to="base.sellerorder",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnlineOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=200, null=True)),
                ("orderType", models.CharField(blank=True, max_length=200, null=True)),
                ("isShipped", models.BooleanField(default=False)),
                ("shippedAt", models.DateTimeField(blank=True, null=True)),
                ("isRetrieved", models.BooleanField(default=False)),
                ("retrievedAt", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.product",
                    ),
                ),
                (
                    "sellerOrder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onlineOrderItems",
                        to="base.sellerorder",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="OrderItem",),
    ]
