# Generated by Django 4.1.3 on 2023-05-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_instoreorderitem_onlineorderitem_delete_orderitem"),
    ]

    operations = [
        migrations.RemoveField(model_name="instoreorderitem", name="isShipped",),
        migrations.RemoveField(model_name="instoreorderitem", name="shippedAt",),
        migrations.RemoveField(model_name="onlineorderitem", name="isRetrieved",),
        migrations.RemoveField(model_name="onlineorderitem", name="isShipped",),
        migrations.RemoveField(model_name="onlineorderitem", name="retrievedAt",),
        migrations.RemoveField(model_name="onlineorderitem", name="shippedAt",),
    ]
