# Generated by Django 4.1.3 on 2023-06-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_instoreorderitem_isshipped_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerorder",
            name="completedAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sellerorder",
            name="isCompleted",
            field=models.BooleanField(default=False),
        ),
    ]
