# Generated by Django 4.1.3 on 2023-05-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="countInStock",),
    ]
