# Generated by Django 4.1.3 on 2023-05-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="store",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="base.store"
            ),
        ),
    ]
