# Generated by Django 4.1.3 on 2023-05-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_remove_orderitem_order_alter_orderitem_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="suborder", name="store",),
    ]
