# Generated by Django 4.1.3 on 2023-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_remove_suborder_store"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="shippingPrice", new_name="totalShippingPrice",
        ),
        migrations.RemoveField(model_name="order", name="deliveredAt",),
        migrations.RemoveField(model_name="order", name="isDelivered",),
        migrations.AddField(
            model_name="suborder",
            name="deliveredAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suborder",
            name="isDelivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suborder",
            name="shippingPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
