# Generated by Django 4.1.3 on 2023-05-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_rename_shippingprice_order_totalshippingprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suborder",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suborders",
                to="base.order",
            ),
        ),
    ]
