# Generated by Django 4.1.3 on 2023-05-17 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0020_alter_suborder_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="user", new_name="customer",
        ),
        migrations.AddField(
            model_name="suborder",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
