# Generated by Django 4.1.3 on 2023-05-17 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_rename_user_order_customer_suborder_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="subOrder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitems",
                to="base.suborder",
            ),
        ),
    ]
