# Generated by Django 4.1.3 on 2023-05-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_alter_orderitem_suborder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suborder", old_name="deliveredAt", new_name="ShippedAt",
        ),
        migrations.RenameField(
            model_name="suborder", old_name="isDelivered", new_name="isShipped",
        ),
    ]
