# Generated by Django 4.1.3 on 2023-05-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_rename_deliveredat_suborder_shippedat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="orderType",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
