# Generated by Django 4.1.3 on 2023-05-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_orderitem_ordertype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suborder", old_name="ShippedAt", new_name="shippedAt",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="totalPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
