# Generated by Django 4.1.3 on 2023-05-25 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_remove_orderitem_totalprice_suborder_totalprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shippingAddress",
                to="base.order",
            ),
        ),
    ]
