# Generated by Django 4.1.3 on 2023-05-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0027_alter_shippingaddress_order"),
    ]

    operations = [
        migrations.RemoveField(model_name="shippingaddress", name="shippingPrice",),
    ]
