name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Add EC2 host to known hosts
      run: ssh-keyscan -H {EC2 Public IP}>> ~/.ssh/known_hosts

      # Deploy to the EC2 instance
    - name: Run deployment script on EC2 instanc
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.195.245.227 << 'EOF'
        cd /home/ubuntu
        chmod +x deploy.sh
        deploy.sh
        EOF
