name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Add EC2 host to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 18.195.245.227 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Run deployment script on EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.195.245.227 << 'EOF'
        cd /home/ubuntu
        chmod +x deploy.sh
        ./deploy.sh
        EOF
