name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run deployment script on EC2
        run: |
          cd /home/ubuntu
          chmod +x deploy.sh
          ./deploy.sh
