name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push backend image
      run: |
        docker build ./backend --file backend/Dockerfile --tag umitcansaran/shopping-land-backend:latest
        docker push umitcansaran/shopping-land-backend:latest

    - name: Build and push frontend image
      run: |
        docker build ./frontend --file frontend/Dockerfile --tag umitcansaran/shopping-land-frontend:latest
        docker push umitcansaran/shopping-land-frontend:latest

    - name: Build and push nginx image
      run: |
        docker build ./nginx --file nginx/Dockerfile --tag umitcansaran/shopping-land-nginx:latest
        docker push umitcansaran/shopping-land-nginx:latest
